version: '2'
services:

  postgres-server:
    image: postgres:10.12-alpine
    command: postgres -c max_connections=500
    restart: always
    stop_grace_period: 1m
    environment:
      - TZ=Etc/UTC
      - PHP_TZ=Etc/UTC
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-5.4.0
    ports:
      - "10051:10051"
    restart: always
    environment:
      - TZ=Etc/UTC
      - PHP_TZ=Etc/UTC
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix

  zabbix-web:
    image:  zabbix/zabbix-web-nginx-pgsql:alpine-5.4.0
    restart: always
    ports:
      - "80:8080"
    environment:
      - TZ=Etc/UTC
      - PHP_TZ=Etc/UTC
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix

  ubuntu:
    build: .
    ports:
      - "2222:22"
